### ISSUE TITLE
Improve the description to setup the project

### ISSUE THREAD

**Issue by landyde** [bertrandpsi/minisimconnect#2]
Hello Bertrand,

Thanks a lot for this project! I am beginner in developing add-ons for FS2020 and I would like to use your project as a first test.
 I am not sure to understand well the steps to set this up:
> Your project must be a 64 bit assembly
> You must have a post build event which copies the DLL and config

Could you provide more details from checking the SDK configuration to building and running the project?

I appreciate your help!

**Comment by bertrand-alain** [comment]
Dear @dylandelaporte ,

Sorry for the late answer, didn't saw your message.
- The DLLs MS provide are 64 bits, that means your .net project must be a 64 bit project only.
- In the project I give, there is a post build event which copies the DLL to your output directory, do the same if you start from scratch. (https://www.quickdevnotes.com/pre-post-build-events-visual-studio/)

Cheers,

Alain
