### ISSUE TITLE
No new Simvars 

### ISSUE THREAD

**Issue by FGET487** [bertrandpsi/minisimconnect#3]
Hi,

I hope I can reach out to you with that. I just found your awesom git repo and the example you provided just works like a charm, but when I try to add more reqested variables (see screenshots), the values are just empty. I tried to query G Force from the Sim, but it keeps being empty...

I also added you on steam, maybe we can discuss about it a bit better over discord or something.

Many thanks in advance!

Greetings,

Tobias
![Unbenannt](https://user-images.githubusercontent.com/31990721/115830320-696b3e00-a410-11eb-9778-10f950e68104.PNG)
![Unbenannt2](https://user-images.githubusercontent.com/31990721/115830323-6a03d480-a410-11eb-8f28-872b7e1c1100.PNG)

**Comment by bertrand-alain** [comment]
The "G Force" requires most likely the unit "G Force" and not just "G" so your row should look like
{6,"G FORCE,G force"}
Those units are defined for example in the units.cs found in "Samples\SimvarWatcher"
Hopefully that helps you ;)

**Comment by FGET487** [comment]
> The "G Force" requires most likely the unit "G Force" and not just "G" so your row should look like
> {6,"G FORCE,G force"}
> Those units are defined for example in the units.cs found in "Samples\SimvarWatcher"
> Hopefully that helps you ;)

That did the trick. Many thanks, and sorry for bothering :)
